#ifndef VMLENS_FLOW_DEFS_H
#define VMLENS_FLOW_DEFS_H

#define DIR_INGRESS 1
#define DIR_EGRESS 2

#define IPPROTO_TCP_VALUE 6
#define IPPROTO_UDP_VALUE 17
#define IPPROTO_ICMP_VALUE 1
#define IPPROTO_ICMPV6_VALUE 58

#define AF_INET_VALUE 2
#define AF_INET6_VALUE 10

#define ETH_P_IP_VALUE 0x0800
#define ETH_P_IPV6_VALUE 0x86DD

#define ETH_HEADER_LEN 14
#define ETH_PROTOCOL_OFFSET 12

#define IPV4_MIN_HEADER_LEN 20
#define IPV4_PROTOCOL_OFFSET 9
#define IPV4_SRC_OFFSET 12
#define IPV4_DST_OFFSET 16

#define IPV6_HEADER_LEN 40
#define IPV6_NEXT_HEADER_OFFSET 6
#define IPV6_SRC_OFFSET 8
#define IPV6_DST_OFFSET 24

#define TCP_FLAGS_OFFSET 13
#define TCP_SYN 0x02
#define TCP_RST 0x04
#define TCP_ACK 0x10

#define TC_ACT_OK 0

#endif // VMLENS_FLOW_DEFS_H
